# generated by datamodel-codegen:
#   filename:  gen_schema.json
#   timestamp: 2024-02-26T03:03:45+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, Field


class Birefringence(BaseModel):
    value: Optional[float] = Field(None, description='', title='Value')
    unit: Optional[str] = Field(None, description='', title='Unit')


class Cutoff(BaseModel):
    value: Optional[float] = Field(None, description='', title='Value')
    unit: Optional[str] = Field(None, description='', title='Unit')


class Eg(BaseModel):
    value: Optional[float] = Field(None, description='', title='Value')
    unit: Optional[str] = Field(None, description='', title='Unit')


class Lidt(BaseModel):
    value: Optional[float] = Field(None, description='', title='Value')
    unit: Optional[str] = Field(None, description='', title='Unit')


class Shg(BaseModel):
    value: Union[float, List[float], None] = Field(None, description='value of shg, must be numerical value, else none', title='Value')
    unit: Optional[str] = Field(None, description='unit of shg', title='Unit')

class ShgValue(BaseModel):
    dij: str = Field(description='different orientation of shg')
    quantity: float = Field(description='the shg corresponds value')

class Compound(BaseModel):
    name: Optional[str] = Field(None, description='the name of compound', title='Name')
    shg: Optional[Shg] = Field(None, description='second harmonic generation')
    eg: Optional[Eg] = Field(None, description='band gap')
    birefringence: Optional[Birefringence] = Field(
        None, description='birefringence of compound'
    )
    cutoff: Optional[Cutoff] = Field(None, description='UV cutoff')
    lidt: Optional[Lidt] = Field(None, description='laser damage threshold')


class Compounds(BaseModel):
    compounds: Optional[List[Compound]] = Field(None, title='Compounds')
