# generated by datamodel-codegen:
#   filename:  js_to_gen.json
#   timestamp: 2024-01-10T09:21:21+00:00

from __future__ import annotations

from typing import List
from typing_extensions import Annotated

from pydantic import BaseModel, AfterValidator

def process_null(value):
    return {"value": None, "unit": None}
def process_null_shg(value):
    return [{"value": None, "unit": None, "dij": None}]

MyNull = Annotated[None, AfterValidator(process_null)]
MyNull_shg = Annotated[None, AfterValidator(process_null_shg)]


class Shg(BaseModel):
    value: float | None | str
    unit: str | None
    dij: str | None


class Eg(BaseModel):
    value: float | None | str
    unit: str | None


class Birefringence(BaseModel):
    value: float | None | str
    unit: str | None


class Lidt(BaseModel):
    value: float | None | str
    unit: str | None

class Cutoff(BaseModel):
    value: float | None | str
    unit: str | None

class Compound(BaseModel):
    name: str
    shg: list[Shg] | MyNull_shg
    eg: Eg | MyNull
    birefringence: Birefringence | MyNull
    cutoff: Cutoff | MyNull
    lidt: Lidt | MyNull


class Model(BaseModel):
    compounds: List[Compound]

# string = """{
#   "compounds": [
#     {
#       "name": "PbB5O7F3",
#       "shg": [
#         {"value": 2.16, "unit": "pm/V", "dij": "d15"},
#         {"value": -0.94, "unit": "pm/V", "dij": "d24"},
#         {"value": -1.44, "unit": "pm/V", "dij": "d33"}
#       ],
#       "eg": null,
#       "birefringence": null,
#       "cutoff": null,
#       "lidt": null
#     },
#     {
#       "name": "KDP",
#       "shg": [{"value": 0.39, "unit": "pm/V", "dij": null}],
#       "eg": null,
#       "birefringence": null,
#       "cutoff": null,
#       "lidt": null
#     },
#     {
#       "name": "CaB5O7F3",
#       "shg": null,
#       "eg": null,
#       "birefringence": null,
#       "cutoff": null,
#       "lidt": null
#     },
#     {
#       "name": "SrB5O7F3",
#       "shg": null,
#       "eg": null,
#       "birefringence": null,
#       "cutoff": null,
#       "lidt": null
#     }
#   ]
# }"""

# import json
# d = json.loads(string)
# nlo_compounds = Model.model_validate(d)
# print(nlo_compounds.model_dump())